trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: infrapipeline
  jobs:
  - job: infraJob
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Hello World"

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/_telcoinfra/Azurerm_resource_group'
        backendServiceArm: 'infracreation'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        workingDirectory: '$(System.DefaultWorkingDirectory)/_telcoinfra/Azurerm_resource_group'
        backendServiceArm: 'infracreation'
