trigger: none
pool: default

stages:
- stage: infrapipeline
  jobs:
  - job: infraJob
    steps:
     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: |
           # Write your PowerShell commands here.
           
           Write-Host "Hello World"